---
title: "rdantic"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rdantic}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rdantic)
library(rlang)
```

## Models

```{r}
person_model <- base_model(
  name = is_scalar_character,
  age = is_scalar_integer
)

(m <- person_model(
  name = "Lee",
  age = 100L
))

try(m$age <- 100)

try(person_model(name = "Lee", age = 100))

# It is also possible to pass lists:
external_data <- list(name = "Morgan", age = 100L)

model_validate(external_data, person_model)
```

## Validators

```{r}
person_model <- base_model(
  name = is_scalar_character,
  age = is_scalar_integer,
  .validators_before = list(
    age = as.integer
  )
)

person_model(name = "Lee", age = 100)
```

## Nested models

```{r}
address_model <- base_model(
  city = is_scalar_character,
  country = is_scalar_character
)

person_model <- base_model(
  name = is_scalar_character,
  age = is_scalar_integer,
  address = is_rdantic_model(address_model)
)

person_model(
  name = "Peter",
  age = 12L,
  address = address_model(
    city = "Kassel",
    country = "Germany"
  )
)

try(person_model(
  name = "Peter",
  age = 12L,
  address = address_model(
    city = c("Kassel", "Berlin"),
    country = "Germany"
  )
))

external_data <- list(
  statusCode = 200L,
  data = list(
    value = 10,
    createdAt = "2024-08-12 20:20:05"
  )
)

data_model <- base_model(
  value = is_scalar_double,
  created_at = is_scalar_character,
  .validators_after = list(
    created_at = as.POSIXct
  )
)

api_model <- base_model(
  status_code = is_scalar_integer,
  data = is_rdantic_model(data_model)
)

external_data |>
  names_to_snake_case() |>
  model_validate(api_model)
```
## Models from templates

```{r}
template <- list(
  a = 10L,
  b = 10L,
  txt = "Some Text"
)

my_model <- model_from_template(template, use_defaults = TRUE)

my_model(a = 5L, b = 10L)

try(my_model(a = 5.5))
```

## From JSON

```{r}
json_str <- '
{
  "a": 10,
  "b": 20,
  "l": [1, 2, 3]
}'

json_model <- base_model(
  a = is_scalar_integer,
  b = is_scalar_integer,
  l = is.integer
)

jsonlite::fromJSON(json_str) |>
  model_validate(json_model)

json_str <- '{"a": 10, "b": 20.5, "l": [1, 2, 3]}'

try(jsonlite::fromJSON(json_str) |> model_validate(json_model))
```

## To JSON

```{r}
my_model <- base_model(
  status_code = model_field(is_scalar_integer, alias = "statusCode"),
  x = ~ is.integer(.x) && length(.x) == 3,
  y = ~ is.integer(.x) && length(.x) == 3
)

my_model(status_code = 200L, x = 1:3, y = 4:6) |>
  model_dump(by_alias = TRUE) |>
  jsonlite::toJSON(auto_unbox = TRUE)
```

## Type safety of function arguments

```{r}
add_two_numbers <- function(a, b) {
  check_args(
    a = is_scalar_double,
    b = is_scalar_double
  )
  a + b
}

add_two_numbers(10, 20)

try(add_two_numbers(10, c(20, 30)))
```

It also possible to add the type checks in this way:

```{r}
add_two_numbers <- function(a = is_scalar_integer,
                            b = is_scalar_integer) {
  check_args()
  a + b
}

add_two_numbers(1L, 3L)

try(add_two_numbers(1L, 4.6))
```

## Data frames

```{r}
cars_model <- base_model(
  speed = is_integer,
  dist = is_integer
)

try(model_validate(cars, cars_model))

cars_model <- base_model(
  speed = is_integer,
  dist = is_integer,
  .validators_before = list(
    speed = as.integer,
    dist = as.integer
  )
)

model_validate(cars, cars_model) |>
  head()
```
